### ISSUE TITLE
Fixes to get app into F-Droid

### ISSUE THREAD

**Issue by mvdan** [Memetro/memetro-android-app#1]
I'm trying to include this app in F-Droid, but there are a few blockers:
- You didn't set a free software license
- You're using crashlytics, which is a non-free library
- You didn't commit your project.properties file
- You're not using git tags to mark releases

Could you please fix these? Thanks!

**Comment by chrbongardt** [comment]
We'll look into it. Thank you!

**Comment by mvdan** [comment]
Bump
